version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: zakydafalas
      POSTGRES_PASSWORD: golang
      POSTGRES_DB: gin_go
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
